modmap:
  - name: Global
    remap:
      CapsLock: Esc
keymap:
  - name: Alt+hjkl to Arrows
    remap:
      # Alt-H: Alt+left #back
      Alt-h: left
      Alt-l: right
      Alt-j: down
      Alt-k: up
      Alt-u: pageup
      Alt-d: pagedown
# keymap:
#   - name: Freetube remap
#    application: 
#     only: FreeTube
#     remap:
#       Alt-h: Left
#       Alt-l: Right
#       Alt-j: Down
#       Alt-k: Up
